version: '3.1'

services:

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nats:
    image: nats:latest
    restart: always
    ports:
      - 4222:4222

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: superSecret123
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080